version: "3"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "/app/node_modules"
      - ".:/app"
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge